---
title: "visuals"
author: "Manye Dong"
date: "2023-09-28"
output: github_document
---
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color=name)) + 
  # can do the color only in geom_point
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  # . means everything displayed to one row, and separate panels regarding names
  facet_grid(. ~ name)
```
```{r}
# refrain from setting colors by hand
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  # the "size" means that 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```
```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax))+
  geom_point(alpha=.3) +
  geom_hex()
```
## Univariate plot: sometimes we only care about max temp
```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .3) +
  
```
```{r}
weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)
```
```{r}
ggp_weather = 
  ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("ggp_weather.pdf", ggp_weather, width = 8, height = 5)
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

```{r, fig.width=3, fig.height=3}

```

